/* eslint-disable */
// @ts-nocheck
// This file is normally auto-generated by TanStack Router.
// Hand-written for first boot; regenerated on dev/build.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as CartRouteImport } from "./routes/cart";
import { Route as OrdersRouteImport } from "./routes/orders";
import { Route as RestaurantIdRouteImport } from "./routes/restaurant.$id";
import { Route as OrderIdRouteImport } from "./routes/order.$id";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);

const CartRoute = CartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => rootRouteImport,
} as any);

const OrdersRoute = OrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => rootRouteImport,
} as any);

const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: "/restaurant/$id",
  path: "/restaurant/$id",
  getParentRoute: () => rootRouteImport,
} as any);

const OrderIdRoute = OrderIdRouteImport.update({
  id: "/order/$id",
  path: "/order/$id",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/search": typeof SearchRoute;
  "/cart": typeof CartRoute;
  "/orders": typeof OrdersRoute;
  "/restaurant/$id": typeof RestaurantIdRoute;
  "/order/$id": typeof OrderIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/search": typeof SearchRoute;
  "/cart": typeof CartRoute;
  "/orders": typeof OrdersRoute;
  "/restaurant/$id": typeof RestaurantIdRoute;
  "/order/$id": typeof OrderIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/search": typeof SearchRoute;
  "/cart": typeof CartRoute;
  "/orders": typeof OrdersRoute;
  "/restaurant/$id": typeof RestaurantIdRoute;
  "/order/$id": typeof OrderIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/search"
    | "/cart"
    | "/orders"
    | "/restaurant/$id"
    | "/order/$id";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/search"
    | "/cart"
    | "/orders"
    | "/restaurant/$id"
    | "/order/$id";
  id:
    | "__root__"
    | "/"
    | "/search"
    | "/cart"
    | "/orders"
    | "/restaurant/$id"
    | "/order/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SearchRoute: typeof SearchRoute;
  CartRoute: typeof CartRoute;
  OrdersRoute: typeof OrdersRoute;
  RestaurantIdRoute: typeof RestaurantIdRoute;
  OrderIdRoute: typeof OrderIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cart": {
      id: "/cart";
      path: "/cart";
      fullPath: "/cart";
      preLoaderRoute: typeof CartRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/orders": {
      id: "/orders";
      path: "/orders";
      fullPath: "/orders";
      preLoaderRoute: typeof OrdersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/restaurant/$id": {
      id: "/restaurant/$id";
      path: "/restaurant/$id";
      fullPath: "/restaurant/$id";
      preLoaderRoute: typeof RestaurantIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/order/$id": {
      id: "/order/$id";
      path: "/order/$id";
      fullPath: "/order/$id";
      preLoaderRoute: typeof OrderIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  CartRoute: CartRoute,
  OrdersRoute: OrdersRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  OrderIdRoute: OrderIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
